name: Fetch Content

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  fetch:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch Content
      run: |
        python get.py
    - name: Commit
      run: |
        git config --global user.email ariel@arielherself.xyz
        git config --global user.name ariel
        git add .
        git commit -m "scheduled update"
        git pull --rebase
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
